# Generated by Django 5.2.6 on 2025-09-26 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.CreateModel(
            name='PrestamoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('activo', 'Activo'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_prestados', to=settings.AUTH_USER_MODEL)),
                ('prestatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Préstamo de Vehículo',
                'verbose_name_plural': 'Préstamos de Vehículos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('manual', 'Registro Manual'), ('automatico', 'Reconocimiento Automático'), ('mixto', 'Verificación Manual + Automática')], default='manual', max_length=15)),
                ('placa_detectada', models.CharField(blank=True, max_length=20, null=True)),
                ('confianza_deteccion', models.FloatField(blank=True, help_text='Nivel de confianza de la detección (0.0 - 1.0)', null=True)),
                ('foto_capturada', models.ImageField(blank=True, null=True, upload_to='accesos/fotos/')),
                ('placa_coincide', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('prestamo_relacionado', models.ForeignKey(blank=True, help_text='Préstamo activo relacionado con este acceso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.prestamovehiculo')),
                ('usuario_autorizado', models.ForeignKey(help_text='Usuario autorizado para usar el vehículo (propietario o prestatario)', on_delete=django.db.models.deletion.CASCADE, related_name='accesos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='vehiculos.vehiculo')),
                ('vigilante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_vigilancia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
