# Generated by Django 5.2.6 on 2025-09-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='fotos_perfil/default.png', upload_to='fotos_perfil/'),
        ),
    ]
