# Generated by Django 5.2.6 on 2025-09-26 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('administrador_general', 'Administrador General'), ('vigilante', 'Vigilante'), ('usuario', 'Usuario')], max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('rol_por_defecto', models.BooleanField(default=False, help_text='Indica si este rol es el rol por defecto para nuevos usuarios.', verbose_name='Rol por Defecto')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol_rol',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='unique_rol_nombre')],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.rol'),
        ),
    ]
